### ISSUE TITLE
Tests werden nicht ausgeführt.

### ISSUE THREAD

**Issue by m-koe** [m-koe/HaskellBlatt1#1]
@mgudemann
Sehr geehrter Herr Prof. Dr. Güdemann, 

leider habe ich ein Problem beim Aufgabenblatt 1 und hoffe das Sie mir weiterhelfen können. Ich bin nun bei der Aufgabe mit dem ggT und habe diesen auch schon geschrieben und mit stack repl ausprobiert. Dort hat alles funktioniert. Zusätzlich habe ich Tests dafür geschrieben. Jedoch beim ausführen der Tests mit stack test bekomme ich als Ergebnis immer nur die Meldung: 
FirstHaskellProjekt> test (suite: FirstHaskellProjekt-test)
Finished in 0.0002 seconds
0 examples, 0 failures
FirstHaskellProjekt> Test suite FirstHaskellProjekt-test passed

Meine Tests werden nicht ausgeführt und ich weiß leider nicht mehr weiter. Ich habe Ihre Schritte nach und nach durchgearbeitet, jedoch komme ich nicht darauf, wieso die Tests nicht ausgeführt werden. Haben sie noch Tipps woran es liegen könnte? 
Vielen Dank! 
Mit freundlichen Grüßen 
Marcel Köhler

**Comment by mgudemann** [comment]
Ich denke das Problem ist, dass das modul `LibSpec` nicht in der Datei `LibSpec.hs` definiert ist, sondern `Spec.hs`.
Die `Spec.hs` Datei sollte nur die Zeile
```
{-# OPTIONS_GHC -F -pgmF hspec-discover #-}
```
enthalten, `LibSpec.hs` dann den Rest.

**Comment by m-koe** [comment]
Perfekt, dass wars. Musste noch die LibSpec.hs Datei hinzufügen und dort die Tests einfügen. Vielen Dank.
